(cl:defpackage chassis_ros-srv
  (:use )
  (:export
   "BATTERY"
   "<BATTERY-REQUEST>"
   "BATTERY-REQUEST"
   "<BATTERY-RESPONSE>"
   "BATTERY-RESPONSE"
   "HEALTH_INFO"
   "<HEALTH_INFO-REQUEST>"
   "HEALTH_INFO-REQUEST"
   "<HEALTH_INFO-RESPONSE>"
   "HEALTH_INFO-RESPONSE"
   "TEST"
   "<TEST-REQUEST>"
   "TEST-REQUEST"
   "<TEST-RESPONSE>"
   "TEST-RESPONSE"
  ))

