// Generated by gencpp from file chassis_ros/health_info.msg
// DO NOT EDIT!


#ifndef CHASSIS_ROS_MESSAGE_HEALTH_INFO_H
#define CHASSIS_ROS_MESSAGE_HEALTH_INFO_H

#include <ros/service_traits.h>


#include <chassis_ros/health_infoRequest.h>
#include <chassis_ros/health_infoResponse.h>


namespace chassis_ros
{

struct health_info
{

typedef health_infoRequest Request;
typedef health_infoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct health_info
} // namespace chassis_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::chassis_ros::health_info > {
  static const char* value()
  {
    return "565180820d1c91abffd3fb243c7cf391";
  }

  static const char* value(const ::chassis_ros::health_info&) { return value(); }
};

template<>
struct DataType< ::chassis_ros::health_info > {
  static const char* value()
  {
    return "chassis_ros/health_info";
  }

  static const char* value(const ::chassis_ros::health_info&) { return value(); }
};


// service_traits::MD5Sum< ::chassis_ros::health_infoRequest> should match
// service_traits::MD5Sum< ::chassis_ros::health_info >
template<>
struct MD5Sum< ::chassis_ros::health_infoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::chassis_ros::health_info >::value();
  }
  static const char* value(const ::chassis_ros::health_infoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::chassis_ros::health_infoRequest> should match
// service_traits::DataType< ::chassis_ros::health_info >
template<>
struct DataType< ::chassis_ros::health_infoRequest>
{
  static const char* value()
  {
    return DataType< ::chassis_ros::health_info >::value();
  }
  static const char* value(const ::chassis_ros::health_infoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::chassis_ros::health_infoResponse> should match
// service_traits::MD5Sum< ::chassis_ros::health_info >
template<>
struct MD5Sum< ::chassis_ros::health_infoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::chassis_ros::health_info >::value();
  }
  static const char* value(const ::chassis_ros::health_infoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::chassis_ros::health_infoResponse> should match
// service_traits::DataType< ::chassis_ros::health_info >
template<>
struct DataType< ::chassis_ros::health_infoResponse>
{
  static const char* value()
  {
    return DataType< ::chassis_ros::health_info >::value();
  }
  static const char* value(const ::chassis_ros::health_infoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CHASSIS_ROS_MESSAGE_HEALTH_INFO_H
