// Generated by gencpp from file chassis_ros/test.msg
// DO NOT EDIT!


#ifndef CHASSIS_ROS_MESSAGE_TEST_H
#define CHASSIS_ROS_MESSAGE_TEST_H

#include <ros/service_traits.h>


#include <chassis_ros/testRequest.h>
#include <chassis_ros/testResponse.h>


namespace chassis_ros
{

struct test
{

typedef testRequest Request;
typedef testResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct test
} // namespace chassis_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::chassis_ros::test > {
  static const char* value()
  {
    return "b57d716f787aff42a104de42df410317";
  }

  static const char* value(const ::chassis_ros::test&) { return value(); }
};

template<>
struct DataType< ::chassis_ros::test > {
  static const char* value()
  {
    return "chassis_ros/test";
  }

  static const char* value(const ::chassis_ros::test&) { return value(); }
};


// service_traits::MD5Sum< ::chassis_ros::testRequest> should match
// service_traits::MD5Sum< ::chassis_ros::test >
template<>
struct MD5Sum< ::chassis_ros::testRequest>
{
  static const char* value()
  {
    return MD5Sum< ::chassis_ros::test >::value();
  }
  static const char* value(const ::chassis_ros::testRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::chassis_ros::testRequest> should match
// service_traits::DataType< ::chassis_ros::test >
template<>
struct DataType< ::chassis_ros::testRequest>
{
  static const char* value()
  {
    return DataType< ::chassis_ros::test >::value();
  }
  static const char* value(const ::chassis_ros::testRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::chassis_ros::testResponse> should match
// service_traits::MD5Sum< ::chassis_ros::test >
template<>
struct MD5Sum< ::chassis_ros::testResponse>
{
  static const char* value()
  {
    return MD5Sum< ::chassis_ros::test >::value();
  }
  static const char* value(const ::chassis_ros::testResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::chassis_ros::testResponse> should match
// service_traits::DataType< ::chassis_ros::test >
template<>
struct DataType< ::chassis_ros::testResponse>
{
  static const char* value()
  {
    return DataType< ::chassis_ros::test >::value();
  }
  static const char* value(const ::chassis_ros::testResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CHASSIS_ROS_MESSAGE_TEST_H
