// Generated by gencpp from file chassis_ros/testRequest.msg
// DO NOT EDIT!


#ifndef CHASSIS_ROS_MESSAGE_TESTREQUEST_H
#define CHASSIS_ROS_MESSAGE_TESTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace chassis_ros
{
template <class ContainerAllocator>
struct testRequest_
{
  typedef testRequest_<ContainerAllocator> Type;

  testRequest_()
    : num1(0)  {
    }
  testRequest_(const ContainerAllocator& _alloc)
    : num1(0)  {
  (void)_alloc;
    }



   typedef int32_t _num1_type;
  _num1_type num1;





  typedef boost::shared_ptr< ::chassis_ros::testRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::chassis_ros::testRequest_<ContainerAllocator> const> ConstPtr;

}; // struct testRequest_

typedef ::chassis_ros::testRequest_<std::allocator<void> > testRequest;

typedef boost::shared_ptr< ::chassis_ros::testRequest > testRequestPtr;
typedef boost::shared_ptr< ::chassis_ros::testRequest const> testRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::chassis_ros::testRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::chassis_ros::testRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::chassis_ros::testRequest_<ContainerAllocator1> & lhs, const ::chassis_ros::testRequest_<ContainerAllocator2> & rhs)
{
  return lhs.num1 == rhs.num1;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::chassis_ros::testRequest_<ContainerAllocator1> & lhs, const ::chassis_ros::testRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace chassis_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::chassis_ros::testRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::chassis_ros::testRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::chassis_ros::testRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::chassis_ros::testRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::chassis_ros::testRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::chassis_ros::testRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::chassis_ros::testRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8ebc68ae8e22b48f76a983ce033a6149";
  }

  static const char* value(const ::chassis_ros::testRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8ebc68ae8e22b48fULL;
  static const uint64_t static_value2 = 0x76a983ce033a6149ULL;
};

template<class ContainerAllocator>
struct DataType< ::chassis_ros::testRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "chassis_ros/testRequest";
  }

  static const char* value(const ::chassis_ros::testRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::chassis_ros::testRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 电池状态 服务\n"
"# 客户端请求时发送\n"
"int32 num1\n"
;
  }

  static const char* value(const ::chassis_ros::testRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::chassis_ros::testRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.num1);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct testRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::chassis_ros::testRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::chassis_ros::testRequest_<ContainerAllocator>& v)
  {
    s << indent << "num1: ";
    Printer<int32_t>::stream(s, indent + "  ", v.num1);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CHASSIS_ROS_MESSAGE_TESTREQUEST_H
